//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyLearnApi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class BADGE_POR_PROYECTO
    {
        public int IdBadge { get; set; }
        public int IdProyecto { get; set; }
        public string Estado { get; set; }
    }
}
