//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyLearnApi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CURSO_POR_PROFESOR
    {
        public int IdCurso { get; set; }
        public string IdProfesor { get; set; }
    
        public virtual CURSO CURSO { get; set; }
    }
}
