//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyLearnApi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ESTUDIANTE
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ESTUDIANTE()
        {
            this.TRABAJO_POR_ESTUDIANTE = new HashSet<TRABAJO_POR_ESTUDIANTE>();
        }
    
        public string Id { get; set; }
        public string NombreContacto { get; set; }
        public string ApellidoContacto { get; set; }
        public string Carne { get; set; }
        public string Email { get; set; }
        public string Telefono { get; set; }
        public string Foto { get; set; }
        public string Pais { get; set; }
        public string Region { get; set; }
        public System.DateTime FechaInscripcion { get; set; }
        public string RepositorioCodigo { get; set; }
        public string LinkHojaDeVida { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TRABAJO_POR_ESTUDIANTE> TRABAJO_POR_ESTUDIANTE { get; set; }
    }
}
