//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyLearnApi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class IDIOMA_POR_ESTUDIANTE
    {
        public string IdEstudiante { get; set; }
        public int IdIdioma { get; set; }
        public string Estado { get; set; }
    
        public virtual ESTUDIANTE ESTUDIANTE { get; set; }
    }
}
