//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyLearnApi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TRABAJO
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TRABAJO()
        {
            this.TRABAJO_POR_ESTUDIANTE = new HashSet<TRABAJO_POR_ESTUDIANTE>();
        }
    
        public int Id { get; set; }
        public string Nombre { get; set; }
        public string Descripcion { get; set; }
        public string IdEmpresa { get; set; }
        public Nullable<System.DateTime> FechaInicio { get; set; }
        public System.DateTime FechaCierre { get; set; }
        public string DocumentoAdicional { get; set; }
        public Nullable<byte> EstrellasObtenidas { get; set; }
        public string Estado { get; set; }
        public Nullable<double> PresupuestoBase { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TRABAJO_POR_ESTUDIANTE> TRABAJO_POR_ESTUDIANTE { get; set; }
    }
}
