//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyLearnApi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class USUARIO:clsJSONResource
    {
        public string Id { get; set; }
        public string RepositorioArchivos { get; set; }
        public string CredencialDrive { get; set; }
        public string Estado { get; set; }
        public string NombreDeUsuario { get; set; }
        public string Contrasena { get; set; }
        public string Sal { get; set; }
    }
}
