//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyLearnApi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class VIEW_CURSOS
    {
        public int IdUniversidad { get; set; }
        public string IdProfesor { get; set; }
        public int IdCurso { get; set; }
        public string NombreCurso { get; set; }
        public string CodigoCurso { get; set; }
        public byte NotaMinima { get; set; }
        public string EstadoCurso { get; set; }
        public Nullable<System.DateTime> FechaInicio { get; set; }
        public Nullable<int> NumeroGrupo { get; set; }
    }
}
